package:
    name: 'asciimatics'
    version: '1.8.0'
source:
    git_rev: "1.8.0"
    git_url: "https://github.com/peterbrittain/asciimatics.git"
requirements:
    build:
        - python
        - setuptools
        - setuptools_scm
        - wcwidth
        - pillow
        - future
        - pyfiglet

    run:
        - python
        - wcwidth
        - pillow
        - future
        - pyfiglet


about:
    home: "https://github.com/peterbrittain/asciimatics"
    license: "Apache 2.0"
    license_file: "LICENSE"
