{% set name = "pyfiglet" %}
{% set version = "0.7.5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "446194e1fc3257ffc8024eafd3b486394847597f6210278d76bd582850205e12" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - pyfiglet = pyfiglet:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyfiglet
    - pyfiglet.fonts
  commands:
    - pyfiglet --help

about:
  home: https://github.com/pwaller/pyfiglet
  license: GNU General Public License v2 or later (GPLv2+)
  license_family: GPL2
  license_file: ''
  summary: Pure-python FIGlet implementation
  description: "All of the documentation and the majority of the work done was by\n    Christopher Jones (cjones@insub.org).\nPackaged by Peter Waller <peter.waller@gmail.com>,\nvarious enhancements by\
    \ Stefano Rivera <stefano@rivera.za.net>.\n\n                        _|_|  _|            _|              _|\n_|_|_|    _|    _|    _|            _|_|_|  _|    _|_|    _|_|_|_|\n_|    _|  _|    _|  _|_|_|_|\
    \  _|  _|    _|  _|  _|_|_|_|    _|\n_|    _|  _|    _|    _|      _|  _|    _|  _|  _|          _|\n_|_|_|      _|_|_|    _|      _|    _|_|_|  _|    _|_|_|      _|_|\n_|              _|          \
    \            _|\n_|          _|_|                    _|_|\n\n\nSYNOPSIS\n\n\tpyfiglet is a full port of FIGlet (http://www.figlet.org/) into pure\n\tpython. It takes ASCII text and renders it in ASCII\
    \ art fonts (like\n\tthe title above, which is the 'block' font).\n\nFAQ\n\n\tQ. Why? WHY?!\n\tA. I was bored. Really bored.\n\n\tQ. What the hell does this do that FIGlet doesn't?\n\tA. Not much, except\
    \ allow your font collection to live\n           in one big zipfile. The point of this code is to embed\n           dynamic figlet rendering in Python without having to\n           execute an external\
    \ program, although it operates on the\n           commandline as well.  See below for USAGE details. You can\n           think of this as a python FIGlet driver.\n\n\tQ. Does this support kerning/smushing\
    \ like FIGlet?\n\tA. Yes, yes it does. Output should be identical to FIGlet. If\n           not, this is a bug, which you should report to me!\n\n\tQ. Can I use/modify/redstribute this code?\n\tA. Yes,\
    \ under the terms of the GPL (see LICENSE below).\n\n\tQ. I improved this code, what should I do with it?\n\tA. You can mail patches to <cjones@insub.org>. Particularly bugfixes.\n           If you\
    \ make changes to the kerning/mushing/rendering portion, PLEASE\n           test it throroughly. The code is fragile and complex.\n\n\nUSAGE\n\n\tYou can use pyfiglet in one of two ways. First, it operates\
    \ on the\n\tcommandline as C figlet does and supports most of the same options.\n\tRun with --help to see a full list of tweaks.  Mostly you will only\n\tuse -f to change the font. It defaults to standard.flf.\n\
    \n\ttools/pyfiglet 'text to render'\n\n\tPyfiglet is also a library that can be used in python code:\n\n\tfrom pyfiglet import Figlet\n\tf = Figlet(font='slant')\n\tprint f.renderText('text to render')\n\
    \n\nAUTHOR\n\n\tpyfiglet is a *port* of FIGlet, and much of the code is directly translated\n\tfrom the C source. I optimized some bits where I could, but because the smushing\n\tand kerning code is\
    \ so incredibly complex, it was safer and easier to port the logic\n\talmost exactly.  Therefore, I can't really take much credit for authorship, just\n\ttranslation. The original authors of FIGlet\
    \ are listed on their website  at\n\thttp://www.figlet.org/.\n\n\tThe Python port was done by Christopher Jones <cjones@insub.org> (http://gruntle.org/).\n\tIt is currently maintained by Peter Waller\
    \ (p@pwaller.net, github:pwaller)\n\n\tThe toilet fonts (.tlf) were imported from toilet 0.3-1, by Sam Hocevar <sam@zoy.org>.\n\nTHANKS\n\n\tgithub:stefanor for various bug fixes and improvements and\
    \ the debian packaging.\n\n\tThanks to anyone who contributed an issue or code on github!\n\nLICENSE\n\n\tCopyright (C) 2007 Christopher Jones <cjones@insub.org>\n\n\tThis program is free software;\
    \ you can redistribute it and/or\n\tmodify it under the terms of the GNU General Public License\n\tas published by the Free Software Foundation; either version 2\n\tof the License, or (at your option)\
    \ any later version.\n\n\tThis program is distributed in the hope that it will be useful,\n\tbut WITHOUT ANY WARRANTY; without even the implied warranty of\n\tMERCHANTABILITY or FITNESS FOR A PARTICULAR\
    \ PURPOSE.  See the\n\tGNU General Public License for more details.\n\n\tYou should have received a copy of the GNU General Public License\n\talong with this program; if not, write to the Free Software\n\
    \tFoundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA\n\n\t(see LICENSE for full details)\n\nCHANGELOG\n\n\t2016-06-12 0.7.5\n        \n            #46 Add 100+ fonts from\
    \ java.de figlet fonts collection v4.0\n            #48 Include python3 in testing\n\n\t2015-05-27 0.7.4\n\n\t    #43 Don't leak file handles\n\n\t2015-04-14 0.7.3\n\n\t    #41 Add newline and text\
    \ wrapping support\n\n\t2014-09-14 0.7.2\n\n\t\t#35 Add this CHANGELOG\n\t\t#36 Bug fix for #34 (broken --reverse and --flip)\n\t\t\t(reported \"character mapping must return integer, None or unicode\"\
    )\n\n\t2014-07-27 0.7.1\n\n\t\t#29 Fix for UTF8 regression\n\t\t#31 Add __main__ entry point\n\t\t#32 Pep8 the code and minor refactoring\n\t\t#33 Trove classifiers update\n\n\t2014-06-02 0.7\n\n\t\t\
    #9 \tAdd --list_fonts and --info_font\n\t\t#10 Add tools/pyfiglet_example for listing all fonts\n\t\t#11 Fix the pyfiglet command (had bad python path)\n\t\t#12 Pyflakes fixes\n\t\t#13 Configure Travis\
    \ Continuous Integration\n\t\t#17 Documentation usage sample fix\n\t\t#19 Enable pyfiglet to use extended ASCII chars\n\t\t#20 Add two cyrillic fonts\n\t\t#21 Python 3 support\n\t\t#27 Code improvements\n\
    \t\t#28 Human readable font list (-l)\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
